### ISSUE TITLE
leapjs-plugins won't work with browserify

### ISSUE THREAD

**Issue by xseignard** [leapmotion/leapjs-plugins#24]
Hello,

Please fix the lib to work with browserify. The `main` in `package.json` and the `index.js` are in an inconsistent state to work with browserify.

Regards,

Xavier

**Comment by xseignard** [comment]
I saw that #19 fixes it, could you publish a new version to npm?

**Comment by pehrlich** [comment]
done - sorry about the delay :)

**Comment by xseignard** [comment]
Thanks :)

**Comment by pehrlich** [comment]
PS if you haven't seen - we're taking feedback, here: https://plus.google.com/u/0/+PeterEhrlichJS/posts/Aes83sr6G5P
