### ISSUE TITLE
some question about screenPosition

### ISSUE THREAD

**Issue by irisred** [leapmotion/leapjs-plugins#25]
I saw screenPosition can change the `hand.palmPosition` into `hand.screenPosition` use the method--screenPosition in the demo, can it be used in gsetures?(such as `keyTap.position`/`screenTap.position`)

**Comment by pehrlich** [comment]
yes, it can.  Simply pass your desired `vec3` as the first argument in the method:

`hand.screenPosition(keyTap.position)`
