### ISSUE TITLE
Tag problem with require via bower installation on client

### ISSUE THREAD

**Issue by kubosador** [leapmotion/leapjs-plugins#26]
If you want to install leapjs-plugins with bower, you download tag v0.1.11 but it does not include "require" correction on leap-plugins-0.1.11.js

**Comment by SantanMaddi** [comment]
Issue is fixed in Clean up THREE node requirement, but these changes are not released/updated in the bower referenced package. Took a while to understand the issue, kindly update the bower package with the latest updates.

**Comment by pehrlich** [comment]
Ah, that was sloppy of me, I'm sorry.  Tag has been updated to the correct commit.  I was able to verify with this:

```
bower uninstall leapjs-plugins
bower cache clean leapjs-plugins
bower install leapjs-plugins
```

Let me know if that works for you

**Comment by SantanMaddi** [comment]
I installed the specific branch from bower. Since you asked I did try with the latest bower package, it works fine now. Thanks @pehrlich
