### ISSUE TITLE
The website has changed, please update the links.

### ISSUE THREAD

**Issue by neolwc** [leapmotion/leapjs-plugins#28]
The [Leap Motion](https://www.leapmotion.com/) website has changed recently and some of the links are not working properly.

**Comment by pehrlich** [comment]
Thanks for the issue!  We'll get those updated pretty quick here now.

**Comment by pehrlich** [comment]
The links are back online, thanks!  Please let me know if there's anything we overlooked.

https://developer.leapmotion.com/javascript#plugins
